### PR TITLE
small fixes to SwissMap.java

### PR DESCRIPTION
**Pull request by rene-mueller**

### CODE REVIEW

**Comment by wipfli** [comment]
Ah cool, thanks for the contribution. Are these the names from the daylight landcover dataset?

**Comment by rene-mueller** [comment]
@wipfli the names are from your filter.py file. So I think they are from the daylight landcover daraset.

**Comment by rene-mueller** [comment]
@wipfli compared to open streetmap, the land and water area is unfortunately not quite optimal. Entire headlands are sometimes missing.

**Comment by wipfli** [comment]
Yeah the land/water polygons maybe don't make a lot of sense because they are too strongly filtered for what one expects. So maybe for land and water people should use a different source...

**Comment by wipfli** [comment]
I am currently running the filter.py script for k=8. I think it will finish in 5 to 7 days. Once that is done, I will review this pull request, merge it and create a new .pmtiles file. Thanks again for your help!

**Comment by rene-mueller** [comment]
@wipfli that sounds great. I build for me mbtiles 😊

**Comment by rene-mueller** [comment]
@wipfli can we merge this?

**Comment by wipfli** [comment]
k=8 finished now so I can review this one now

**Review by wipfli — APPROVED** [review]

**Comment by wipfli** [comment]
Thanks for your contribution @rene-mueller!

**Pull request merged**
